version: "3.7"
services:
  rabbitmq:
    container_name: rabbitmq
    build: rabbitmq
    hostname: rabbitmq
    restart: always
    privileged: true
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  redis:
    container_name: redis
    build: redis
    hostname: redis
    restart: always
    privileged: true
    ports:
      - "6379:6379"
    networks:
      - network
    volumes:
      - redis_data:/var/lib/data
  mysql:
    container_name: mysql
    build: mysql
    hostname: mysql
    restart: always
    privileged: true
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - "3306:3306"
    networks:
      - network
    volumes:
      - mysql_data:/var/lib/mysql/
networks:
  network:
    driver: bridge
    name: network
volumes:
  rabbitmq_data: {}
  redis_data: {}
  mysql_data: {}


