FROM elasticsearch:7.6.2
RUN cp /usr/share/elasticsearch/config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml.bak \
    && cp /usr/share/elasticsearch/config/jvm.options /usr/share/elasticsearch/config/jvm.options.bak
COPY ./elasticsearch.yml /usr/share/elasticsearch/config/
COPY ./jvm.options /usr/share/elasticsearch/config/
COPY ./elasticsearch-analysis-ik-7.4.0.zip /usr/share/elasticsearch/plugins/ik/
EXPOSE 9200 9300
ENV TZ Asia/Shanghai
ENV discovery.type single-node
CMD [ "elasticsearch" ]

